dist: bionic

jobs:
  include:
  - name: Kong CE 2.4.x
    env: KONG_VERSION=2.4.x
  - name: Kong EE 2.4.1.x
    env: KONG_VERSION=2.4.1.x
  - name: Kong EE 1.5.0.x
    env: KONG_VERSION=1.5.0.x
  - name: Nightly EE-master
    env: KONG_VERSION=nightly-ee POSTGRES=latest CASSANDRA=latest
  #- name: Nightly CE-master
  #  env: KONG_VERSION=nightly POSTGRES=latest CASSANDRA=latest

install:
- git clone --single-branch https://github.com/Kong/kong-pongo ../kong-pongo
- "../kong-pongo/pongo.sh up"
- "../kong-pongo/pongo.sh build"

script:
- "../kong-pongo/pongo.sh lint"
- "../kong-pongo/pongo.sh run"

notifications:
  slack:
    if: branch = master AND type != pull_request
    on_success: change
    on_failure: always
    rooms:
      secure: Po86JTRkr5/VkRFqu4Wmksa/GVBqDUPfeFsB75vR+PTsCKEboALGszLZRAxBSrb/xl9gzX4XhddiYc98Bw9tkoD68h3kGkmvq+HJA0od0/Zbhh3+Ono5RjFukXFCFXJUPMFA/zBVAeXZhiceEwdOdxTPI58YPiiE9yobJfHuZmxMOWEhIFMDBgbJ5PIYWWkggXeYBjbN5+WIdBhcApMe296LgmXVch2KqSX+asfW6rz7g6h/rD+e2dDO7kASSkGzLfGe3bf07p7Wqy1AIz4mB5uRnsBqNYxjqTXDKfRJnBh99hlzFUIOw/IJl8+UvlM8Ade2n9SHoJw87XDl9h9Gfdvk+ASx6h1GUNtr6j8k7HlsEJLirA7pirdAjck+/xjgzp1DjGSQPu2qjT6Ueg2/Szfv8pZ6ZnYi/zBmpY3S/VHE06UbAnK9IcWAbwWhKKSwnyFZXVeFhUIe9yeqjAx9SBz+q0pC3rS51WhbzJJwe6vAmkJSbR8mSPh/LG63xxZIfu5tq9lPJWOdFq2WymOje62oxXsr67X2xFGTTwhRnqlUwDsyuKJaPRPOHV5+9cyBLI4pxcKUIymOfEjuPfAdHv5YaITL56ZBvGkW+W35boDlXLVXtN3Qc0MpA+7uHzrEg6KQ5DwUdj8cgXoDoh6QQN5wF4Spz7zyygBXWpTNjus=
